#  Copyright © 2023 ROBOMASTER All Rights Reserved.
#  You may use, distribute and modify this code under the
#  terms of the MIT license, which unfortunately won't be
#  written for another century.

%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"



# Rectified Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 382.328
Camera1.fy: 382.328
Camera1.cx: 319.108
Camera1.cy: 236.605

Camera2.fx: 382.328
Camera2.fy: 382.328
Camera2.cx: 319.108
Camera2.cy: 236.605


Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.k3: 0.0
Camera1.k4: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.k3: 0.0
Camera1.k4: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

Stereo.T_c1_c2:
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0,0.0, 0.0500961,
         0.0,1.0,0.0, 0.0,
         0.0,0.0,1.0,0.0,
         0.0,0.0,0.0,1.0]

Stereo.b: 0.0500961



# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 12

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 100.0

# Lapping area between images (We must calculate)
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 639

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 639


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 600 #1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
